import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import{ Header } from "@/components/Header"

import { Rubik } from 'next/font/google';

import "./globals.css";

const rubik = Rubik({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={rubik.className}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
        <Header></Header>
        {children}
      </ThemeProvider>

      </body>
    </html>
  );
}
